spec-version: 0.34.2
name: tasty-json-reporter
version: 0.0.0
synopsis: A Tasty reporter that outputs JSON or Markdown
description: |
  This package provides a Tasty reporter that outputs JSON or Markdown.
  It is intended to be used with the [Tasty](https://hackage.haskell.org/package/tasty) test framework.
maintainer: Connor Baker <connorbaker01@gmail.com>
github: connorbaker/tasty-json
category: Development

ghc-options: -Wall

dependencies:
  - aeson
  - base >= 4.9 && < 5
  - bytestring
  - containers
  - optparse-applicative
  - stm
  - tagged
  - tasty
  - text
  - unordered-containers

library:
  source-dirs: .
