name: Setup
description: "Setup the GitHub Actions environment with nix."

inputs:
  REPO_AUTH_TOKEN:
    description: "The GitHub repository authentication token."
    required: true

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@v17
      with:
        # The action automatically adds max-jobs and experimental-features,
        # but we choose to keep them for those looking for an easy configuration
        # to copy-paste from.
        # Note that the action also adds trusted-users so we can access the binary
        # cache.
        extra_nix_config: |
          access-tokens = github.com=${{ inputs.REPO_AUTH_TOKEN }}
          experimental-features = nix-command flakes
          max-jobs = auto
          http-connections = 0
          substitute = true
          fallback = true
          keep-outputs = false
          keep-derivations = false
          substituters = https://cache.iog.io https://iohk.cachix.org https://cache.nixos.org/ https://nix-community.cachix.org https://haskell-language-server.cachix.org https://haskell-library-tasty-json.cachix.org
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= haskell-language-server.cachix.org-1:juFfHrwkOxqIOZShtC4YC1uT1bBcq2RSvC7OMKx0Nz8= haskell-library-tasty-json.cachix.org-1:srj2Qko32LAYrp8ZumHEZll3KSnc1ysPlT8Z5iebiXY=
