spec-version: 0.34.2
name: tasty-json-reporter
version: 0.0.0
synopsis: A Tasty reporter that outputs JSON or Markdown
description: |
  This package provides a Tasty reporter that outputs JSON or Markdown.
  It is intended to be used with the [Tasty](https://hackage.haskell.org/package/tasty) test framework.
maintainer: Connor Baker <connorbaker01@gmail.com>
github: connorbaker/tasty-json-reporter
category: Development
extra-source-files:
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - aeson
  - base >= 4.9 && < 5
  - bytestring
  - tasty
  - text

library:
  source-dirs: tasty-json-reporter
  dependencies:
    - containers
    - optparse-applicative
    - stm
    - tagged
    - unordered-containers

tests:
  tasty-json-reporter-test:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - tasty-hunit
      - tasty-json-reporter
